### PR TITLE
Added PULP_MANIFEST.asc to mutable_urls in file repo

### PR DESCRIPTION
**Pull request by midnightercz**

### CODE REVIEW

**Comment by rohanpm** [comment]
The Github Ubuntu runners seem to have problems installing various packages.  Will check if the problem goes away by itself in a day or two before investigating further.

**Comment by rohanpm** [comment]
This will need https://github.com/release-engineering/pubtools-pulplib/pull/216 to be submitted first to fix CI, then this can be rebased on top.

**Comment by rohanpm** [comment]
Please rebase this now so we can get a fresh CI run.

**Comment by midnightercz** [comment]
rebased

**Review by rohanpm — APPROVED** [review]

**Pull request merged**
